import { ICommand, CommandContext, CommandResult } from '../ICommand';
import * as vscode from 'vscode';

/**
 * InitCommand: 初始化 Opengravity 标准工作流
 * 创建核心 6 文件夹架构并生成项目规范
 */
export class InitCommand implements ICommand {
    name = 'init';
    description = '初始化 Opengravity 标准工作流目录结构';

    private readonly CORE_FOLDERS = [
        'codes',
        'brainstorm',
        'daily',
        'notes',
        'reviews',
        'todo'
    ];

    private readonly SKILL_FOLDERS = [
        'skills',
        'agents',
        'codingstyle',
        'commands'
    ];

    async execute(args: string[], context: CommandContext): Promise<CommandResult> {
        const rootPath = vscode.workspace.workspaceFolders?.[0]?.uri;
        if (!rootPath) {
            return { status: 'error', message: '❌ 当前未打开任何工作区，无法初始化。' };
        }

        // 1. 用户确认
        const confirm = await vscode.window.showWarningMessage(
            '[🚀] 确认在该工作区初始化 Opengravity 工作流?\n这将创建核心文件夹及 .opengravity 配置库。',
            { modal: true },
            '立即初始化'
        );

        if (confirm !== '立即初始化') {
            return { status: 'intercepted', message: '用户已取消。' };
        }

        try {
            // 2. 创建核心 6 文件夹
            for (const folder of this.CORE_FOLDERS) {
                const folderUri = vscode.Uri.joinPath(rootPath, folder);
                await vscode.workspace.fs.createDirectory(folderUri);
            }

            // 3. 创建 .opengravity 内部技能库
            const configDir = vscode.Uri.joinPath(rootPath, '.opengravity');
            for (const folder of this.SKILL_FOLDERS) {
                const folderUri = vscode.Uri.joinPath(configDir, folder);
                await vscode.workspace.fs.createDirectory(folderUri);
            }

            // 4. 生成 .opengravity/GEMINI.md 模板
            await this.generateGeminiDoc(rootPath);

            const successMsg = [
                "### 🎉 工作流空间初始化成功！",
                "",
                "**1. 核心工作流：**",
                "- `codes/`, `brainstorm/`, `daily/`, `notes/`, `reviews/`, `todo/`",
                "",
                "**2. 技能系统 (.opengravity/)：**",
                "- `skills/`: 存放具体的 Skill Markdown 模板",
                "- `agents/`: 存放 AI 角色定义",
                "- `codingstyle/`: 存放团队代码规范",
                "- `commands/`: 存放自定义 .toml 指令",
                "",
                "您可以开始在 `commands/` 下编写指令并引用其他目录中的模板了。"
            ].join('\n');

            await context.webview.postMessage({
                type: 'aiResponse',
                value: successMsg
            });

            return { status: 'success' };

        } catch (error: any) {
            return { status: 'error', message: `❌ 初始化失败: ${error.message}` };
        }
    }

    private async generateGeminiDoc(rootUri: vscode.Uri) {
        const geminiDir = vscode.Uri.joinPath(rootUri, '.opengravity');
        const geminiDoc = vscode.Uri.joinPath(geminiDir, 'GEMINI.md');

        const template = [
            "# Project Context (GEMINI.md)",
            "",
            "## 🧠 开发约定 (Memories)",
            "- 禁止任何假设，面对未知时询问用户。",
            "- 效率低下和遇到挫折往往来源于假设，信息不足。",
            "",
            "---",
            "*This file is auto-generated by Opengravity.*"
        ].join('\n');

        const encoder = new TextEncoder();
        await vscode.workspace.fs.writeFile(geminiDoc, encoder.encode(template));
    }
}
